<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-O2MUR00" failures="1" tests="1" name="Test" time="0.518" errors="0" timestamp="2023-07-19T17:19:36 IST">
  <testcase classname="com.sb.testcases.Tc_data" name="TC_RF_002" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
at com.sb.baseclass.extelutils.getTestData(extelutils.java:35)
at com.sb.testcases.Tc_data.getLoginData(Tc_data.java:30)
... 25 more
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- TC_RF_002 -->
</testsuite> <!-- Test -->
